language: node_js
sudo: required
node_js:
  - 5
  - 6
  - 7

cache:
  directories:
    - node_modules
    - $HOME/.yarn-cache

before_install:
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - yarn -V

install:
  - yarn

script:
  - yarn test

deploy:
  provider: npm
  email: lamo2k123@gmail.com
  api_key: $NPM_API_KEY
  on:
    tags: true
    node: 6
    repo: lamo2k123/daemon-command-webpack-plugin

os:
  - linux
